{{- range $k, $v := .Values.ingress_types.apim }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $k }}
  namespace: shared-components
spec:
  provider: azure
  secretObjects:                             
  - data:
    - key: {{ $k }}                          
      objectName: {{ $k }}        
    secretName: {{ $k }}   
    type: Opaque  
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: {{ $.Values.shared_identity_client_id }}
    keyvaultName: {{ $.Values.shared_keyvault_name }}
    objects:  |
      array:
        - |
          objectName: {{ $k }}
          objectType: secret  
          objectVersion: ""  
    tenantId: {{ $.Values.tenant_id }}
---
{{- end }}