apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-key-vault
  namespace: app201
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: {{ .Values.identity_client_id_app201 }}
    keyvaultName: {{ .Values.key_vault_name_app201 }}
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: mysecret
          objectType: secret  
          objectVersion: ""  
    tenantId: {{ .Values.tenant_id }}
---
kind: Pod
apiVersion: v1
metadata:
  name: client-secrets
  namespace: app201
spec:
  serviceAccountName: application
  containers:
    - name: client
      image: nginx:latest
      volumeMounts:
      - name: mysecretmount
        mountPath: "/mnt/mysecretpath"
        readOnly: true
  volumes:
    - name: mysecretmount
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: azure-key-vault