# Provider class that is trying to access someone else Key Vault and identity
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-key-vault-misuse
  namespace: app102
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: {{ .Values.identity_client_id_app101 }}
    keyvaultName: {{ .Values.key_vault_name_app101 }}
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: mysecret
          objectType: secret  
          objectVersion: ""  
    tenantId: {{ .Values.tenant_id }}
---
# Service Account trying to map someone elses identity
apiVersion: v1
kind: ServiceAccount
metadata:
  name: application-attack
  namespace: app102
  annotations:
    azure.workload.identity/client-id: {{ .Values.identity_client_id_app101 }}
  labels:
    azure.workload.identity/use: "true"
---
kind: Pod
apiVersion: v1
metadata:
  name: client-secrets-misuse
  namespace: app102
spec:
  serviceAccountName: application-attack
  containers:
    - name: client
      image: nginx:latest
      volumeMounts:
      - name: mysecretmount
        mountPath: "/mnt/mysecretpath"
        readOnly: true
  volumes:
    - name: mysecretmount
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: azure-key-vault-misuse