{{- range $k, $v := .Values.standard_applications }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $k }}
  namespace: {{ $k }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              sas: {{ $k }}
        {{- range $ingress_type := $v.ingress_types }}
        - namespaceSelector:
            matchLabels:
              sas: shared
          podSelector:
            matchLabels:
              ingress_type: {{ $ingress_type }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
---
{{- end }}

{{- range $k, $v := .Values.confidential_applications }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $k }}
  namespace: {{ $k }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              sas: {{ $k }}
        {{- range $ingress_type := $v.ingress_types }}
        - namespaceSelector:
            matchLabels:
              sas: shared
          podSelector:
            matchLabels:
              ingress_type: {{ $ingress_type }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
---
{{- end }}