apiVersion: apps/v1
kind: Deployment
metadata:
  name: app103
  namespace: app103
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app103
  template:
    metadata:
      labels:
        app: app103
    spec:
      initContainers:
      - name: init-nginx
        image: busybox
        command: ['sh', '-c', 'echo "Hello from app103" > /usr/share/nginx/html/index.html']
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app103
  namespace: app103
spec:
  selector:
    app: app103
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app103
  namespace: app103
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-ingress-external
  rules:
  {{- $ip_map := first (lookup "v1" "Service" "shared-components" "nginx-ingress-external-ingress-nginx-controller").status.loadBalancer.ingress }}
  - host: app103.{{ $ip_map.ip  }}.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app103
            port:
              number: 80