name: Create cluster01
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: demo
    permissions:
      id-token: write
    steps:
    
    - name: Checkout
      uses: actions/checkout@v1