name: Destroy landing zone for demo
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: demo
    permissions:
      id-token: write
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform Init
      working-directory: ./landing_zone
      run: terraform init -backend-config=client_id=${{ secrets.AZURE_CLIENT_ID }} -backend-config=tenant_id=${{ secrets.AZURE_TENANT_ID }}

    - name: Terraform Destroy
      working-directory: ./landing_zone
      run: terraform destroy -auto-approve

    - name: List repo runners
      uses: octokit/request-action@v2.x
      id: list_runners_token
      with:
        route: GET /repos/tkubica12/aks-as-a-service/actions/runners
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Parse first runner id
      uses: sergeysova/jq-action@v2
      id: parse_runner_id
      with:
        cmd: echo '${{ steps.list_runners_token.outputs.data }}' | jq .runners[0].id -r

    - name: Delete repo runner
      uses: octokit/request-action@v2.x
      id: delete_runner
      with:
        route: DELETE /repos/tkubica12/aks-as-a-service/actions/runners/${{ steps.parse_runner_id.outputs.value }}
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    # - name: Delete runner client ID as repo variable
    #   uses: octokit/request-action@v2.x
    #   with:
    #     route: DELETE /repos/tkubica12/aks-as-a-service/actions/variables/runner_client_id
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.PAT }}